#!/bin/bash
cd web_client
npm install
npm audit fix
npm run build
echo "created build"
sudo mv /var/www/memechampion.com/images /var/www/images
echo "moving old images into safe folder"
sudo rm -r /var/www/memechampion.com/*
echo "clearing main directory"
sudo mv build/* /var/www/memechampion.com/
echo "moving build contents to main directory"
sudo mv /var/www/images /var/www/memechampion.com/images
echo "moving back images into correct folder"
sudo chown -R ubuntu /var/www/memechampion.com/images
echo "making permisions correct"
cd /var/www/memechampion.com

echo "creating images directory and creating ownership"
sudo cat > .htaccess <<- "EOF"

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /subdirectory
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-l
RewriteRule . /index.html [L]
</IfModule>

EOF
echo "creating .htaccess file"

sudo /etc/init.d/apache2 restart
echo "restarting server"
