#!/bin/bash
cd web_client
npm install
npm run build
echo "created build"
sudo rm -r /var/www/memechampion.com/*
echo "clearing main directory"
sudo mv build/* /var/www/memechampion.com/
echo "moving build contents to main directory"
sudo mkdir /var/www/memechampion.com/images/
sudo chown -R ubuntu /var/www/memechampion.com/images
echo "creating images directory and creating ownership"
sudo /etc/init.d/apache2 restart
echo "restarting server"
